### ISSUE TITLE
Bookmark creation fails because of null cache key

### ISSUE THREAD

**Issue by thierrymarianne** [idno/like#3]
After looking into this error `Cache key must be string, "NULL" given`,

I've figured the retrieval of a page title can fail because of a URL valued to `null`.

Here is a quick fix applied to this plugin: https://github.com/thierrymarianne/withknown-like/commit/dd9283c83ff030f6b3660b429a46f5700e226c07

Please let me know if there would be another patch better fitting with the problem at hand,
provided that another fix could consist in applying a similar patch to 
`Idno\Core\Webservice->file_get_contents`

**Comment by johanbove** [comment]
This seems valid. Thanks @thierrymarianne . Trying it out on my Known instance.

**Comment by johanbove** [comment]
We would need a test case to verify this works fine. Will see to set up a "title" -less page later today.

**Comment by mapkyca** [comment]
Have you tried the latest build? I fixed an issue with HSTS a few days ago

**Comment by thierrymarianne** [comment]
@mapkyca `1.0.0-rc.1` was checked out. I will try again this evening from `master`.

**Comment by johanbove** [comment]
[@mapkyca](https://github.com/mapkyca) How is HSTS involved in this? Are you referring to HTTP Strict Transport Security?

(Originally published at: https://social.johanbove.info/2019/10/16/mapkyca-how-is-hsts-involved-in-this)

**Comment by mapkyca** [comment]
Yep.

The bookmark code attempts to fetch the linked thing in the background, but because of some dumb javascript it tries to fetch a blank string which causes the web services subsystem to shit the bed.

**Comment by thierrymarianne** [comment]
It sounds like the issue I encountered on the endpoint ending with `edit` - an asynchronous request was indeed provoking an error when clicking on `bookmark`.

**Comment by thierrymarianne** [comment]
The `master` branch of `https://github.com/idno/known` has this issue fixed.

Thanks.

**Comment by johanbove** [comment]
@thierrymarianne Thanks. To understand what resolved the issue: what exactly was changed in the master branch that fixed this?

**Comment by mapkyca** [comment]
Basically short circuiting the hsts header handling if no domain is passed

**Comment by thierrymarianne** [comment]
@johanbove I didn't check which changes is responsible for fixing the issue. 
Thanks @mapkyca for answering the question o/
